import Vue from "vue"
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
import { library, dom } from "@fortawesome/fontawesome-svg-core"
import {
  faBars,
  faChevronLeft,
  faChevronRight,
  faCaretLeft,
  faCaretRight,
  faPen,
  faThumbsUp,
  faCommentAltDots,
  faReply,
  faColumns,
  faHeart,
  faExclamationTriangle,
  faSortDown,
  faFilePdf,
  faFilePowerpoint,
  faFileDownload,
  faFileExcel,
  faDownload as fasDownload,
  faUserPlus,
  faExternalLink,
  faFileVideo,
  faLongArrowDown,
  faMegaphone as fasMegaphone,
  faEdit as fasEdit,
  faUserAlt,
  faPlayCircle as fasPlayCircle,
  faBackward,
  faPollH,
  faArrowLeft as fasArrowLeft,
} from "@fortawesome/pro-solid-svg-icons"
import {
  faExpand,
  faDownload,
  faHistory,
  faThumbsUp as falThumbsUp,
  faMegaphone,
  faCalendarCheck,
  faSignInAlt,
  faSignOutAlt,
  faUpload,
  faListOl,
  faInfoSquare,
  faAngleLeft,
  faAngleRight,
  faArrowLeft,
  faExternalLinkAlt,
  faMicrophoneAlt,
  faSearch,
  faAngleDown,
  faArrowCircleRight,
  faHandPointer,
  faCircle,
  faTimes,
  faSlidersV,
  faCalendarPlus,
  faClock,
  faLink,
  faUsers,
  faPlayCircle,
  faBan,
  faRedo,
  faSmile,
  faFrown,
  faPollH as faPollHLight,
  faPlus,
} from "@fortawesome/pro-light-svg-icons"
import {
  faTrashAlt,
  faEdit,
  faImage,
  faPlusCircle,
  faImages,
  faExclamationTriangle as farExclamationTriangle,
  faCircle as farCircle,
  faTimes as farTimes,
  faHeart as farHeart,
  faSearchPlus,
  faSearchMinus,
  faBook,
  faUniversity,
  faCalendarAlt,
  faChairOffice,
} from "@fortawesome/pro-regular-svg-icons"
import {
  faUserCircle,
  faCheckCircle,
  faSpinnerThird,
  faAngleDoubleLeft,
  faDownload as fadDownload,
} from "@fortawesome/pro-duotone-svg-icons"

Vue.component("font-awesome-icon", FontAwesomeIcon)

//todo 이거 일일이 등록하지 않으면서 쓰는 것만 골라낼 방법이 있을까?
library.add(
  faChairOffice,
  faCalendarAlt,
  faBars,
  faChevronLeft,
  faChevronRight,
  faCaretLeft,
  faCaretRight,
  faPen,
  faThumbsUp,
  faCommentAltDots,
  faExpand,
  faDownload,
  falThumbsUp,
  faHistory,
  faReply,
  faMegaphone,
  faTrashAlt,
  faEdit,
  faColumns,
  faBan,
  faCalendarCheck,
  faSignInAlt,
  faSignOutAlt,
  faUserCircle,
  faHeart,
  faUpload,
  faImage,
  faListOl,
  faInfoSquare,
  faPlusCircle,
  faAngleLeft,
  faArrowLeft,
  faPollH,
  faExclamationTriangle,
  faExternalLinkAlt,
  faMicrophoneAlt,
  faSearch,
  faAngleDown,
  faArrowCircleRight,
  faHandPointer,
  faCircle,
  faCheckCircle,
  faSpinnerThird,
  faAngleDoubleLeft,
  fadDownload,
  faTimes,
  faSlidersV,
  faSortDown,
  fasDownload,
  faUserPlus,
  faLongArrowDown,
  fasMegaphone,
  fasEdit,
  faCalendarPlus,
  faClock,
  faLink,
  faUsers,
  faImages,
  faPlayCircle,
  faBan,
  faRedo,
  faSmile,
  faFilePdf,
  faFilePowerpoint,
  faFileDownload,
  faFileExcel,
  faFileVideo,
  faExternalLink,
  farExclamationTriangle,
  farCircle,
  farTimes,
  farHeart,
  faSearchPlus,
  faSearchMinus,
  faAngleRight,
  faUserAlt,
  fasPlayCircle,
  faUniversity,
  faBook,
  faBackward,
  faPollHLight,
  fasArrowLeft,
  faPlus,
  faFrown,
)
dom.watch()
